"""Merge Suno prompt fragments into Flutter + server SYSTEM_PROMPT_V2 / V4 architecture.

Edit sources under tools/ (see tools/README.md), then run:

    python tools/merge_suno_v2_prompt.py

Full rebuild (prompts + matrix Dart): python tools/merge_all.py
"""

from __future__ import annotations

import pathlib
import sys

root = pathlib.Path(__file__).resolve().parents[1]


def _read(name: str) -> str:
    path = root / "tools" / name
    if not path.is_file():
        raise SystemExit(f"Missing required source: tools/{name}")
    return path.read_text(encoding="utf-8")


def main() -> None:
    p1_text = _read("suno_v2_p1.txt")
    idx = p1_text.find("\n\n")
    if idx < 0:
        raise SystemExit("suno_v2_p1.txt: need a blank line after the role paragraph")
    role_block = p1_text[: idx + 2]
    p1_rest = p1_text[idx + 2 :]

    p2_core = (
        _read("elite_human_lyricist_directive.txt")
        + "\n\n"
        + _read("human_authenticity_engine.txt")
        + "\n\n"
        + _read("nigeria_cultural_realism_engine.txt")
        + "\n\n"
        + _read("genre_specific_humanization_engine.txt")
        + "\n\n"
        + _read("human_songwriter_engine_v3.txt")
        + "\n\n"
        + _read("suno_v2_p2_block2_protocol.txt")
    )

    mid = (
        p2_core
        + "\n"
        + _read("suno_v2_melody_sync_lyric_engine.txt")
        + "\n"
        + _read("suno_v2_p2_section2_unified.txt")
        + "\n"
        + _read("suno_v2_block2_arrangement_staging_format.txt")
        + "\n"
        + _read("suno_v2_block2_genre_structures.txt")
        + "\n"
        + _read("suno_v2_genre_specific_lyrics_prompts.txt")
        + "\n"
        + _read("suno_v2_block1_genre_examples.txt")
        + "\n"
        + _read("suno_v2_suno_signal_principles.txt")
        + "\n"
        + _read("suno_v2_p3.txt")
        + _read("suno_v2_p4.txt")
        + "\n"
        + _read("suno_v2_live_instrument_protocol.txt")
        + "\n"
        + _read("suno_v2_genre_mastering_mixing_blueprints.txt")
    )

    # Merge order follows docs/CREATION_PIPELINE.md (pipeline header → DNA → genre → intelligence → lyrics → Suno output).
    body = (
        role_block
        + _read("suno_v4_master_production_architecture.txt")
        + "\n"
        + _read("suno_v2_p0_format_law.txt")
        + "\n"
        + _read("pipeline_architecture.txt")
        + "\n"
        + _read("artist_dna_translation_engine.txt")
        + "\n"
        + _read("suno_v2_architect_vault_snapshot.txt")
        + "\n"
        + p1_rest
        + "\n"
        + _read("suno_v2_code_translation_protocol.txt")
        + "\n"
        + _read("suno_v2_lyrics_style_full_engine.txt")
        + "\n"
        + _read("suno_v2_variation_engine.txt")
        + "\n"
        + _read("suno_v2_advanced_creative_layers.txt")
        + "\n"
        + _read("suno_v2_edm_production_engine.txt")
        + "\n"
        + _read("suno_v2_genre_gear_mapping.txt")
        + "\n"
        + _read("suno_v2_hardware_qc_engine.txt")
        + "\n"
        + _read("suno_v2_style_narrative_modules_abcd.txt")
        + "\n"
        + _read("suno_v2_dj_intro_outro_suno_module.txt")
        + "\n"
        + _read("music_creation_intelligence_engine.txt")
        + "\n"
        + _read("hit_song_psychology_engine.txt")
        + "\n"
        + mid
    )

    header = """// ignore_for_file: lines_longer_than_80_chars
//
// **Generated** — do not edit by hand. Sources: tools/README.md
// Rebuild: python tools/merge_suno_v2_prompt.py
//
// Flutter: USE_SUNO_PROMPT_V2 in .env (default on). Server: same env on Railway.

const String kSunoDirectorSystemPromptV2Candidate = r'''
"""
    footer = "''';\n"

    dart_path = root / "lib/core/constants/suno_system_prompt_v2_candidate.dart"
    dart_path.write_text(header + body + footer, encoding="utf-8")

    py_path = root / "server/app/suno_system_prompt_v2.py"
    py_path.write_text(
        '"""Suno V4 master production prompt — generated by tools/merge_suno_v2_prompt.py."""\n\n'
        'SYSTEM_PROMPT_V2 = """\n'
        + body
        + '\n"""\n\n'
        '# Alias for V4 architecture consumers\n'
        'SYSTEM_PROMPT_V4 = SYSTEM_PROMPT_V2\n',
        encoding="utf-8",
    )

    elite_src = _read("elite_human_lyricist_directive.txt")
    elite_dart = root / "lib/core/constants/elite_human_lyricist_directive.dart"
    elite_dart.write_text(
        "// ignore_for_file: lines_longer_than_80_chars\n"
        "//\n"
        "// **Generated** — do not edit by hand. Source: tools/elite_human_lyricist_directive.txt\n"
        "// Rebuild: python tools/merge_suno_v2_prompt.py\n"
        "\n"
        "/// Elite human lyricist core — Block 2 authenticity.\n"
        "class EliteHumanLyricistDirective {\n"
        "  EliteHumanLyricistDirective._();\n"
        "\n"
        "  static const String directive = r'''\n"
        + elite_src
        + "\n''';\n"
        "\n"
        "  static String userBlockPrefix() =>\n"
        "      'ELITE HUMAN LYRICIST (Block 2 — mandatory craft layer; "
        "maintain genre conventions):\\n$directive';\n"
        "}\n",
        encoding="utf-8",
    )

    print(
        f"Wrote {dart_path.relative_to(root)}, {py_path.relative_to(root)}, "
        f"and {elite_dart.relative_to(root)} "
        f"({len(body)} chars, {len(body.splitlines())} lines)"
    )


if __name__ == "__main__":
    main()
    sys.exit(0)
